### ISSUE TITLE
Text inserter needs better window geometry awareness

### ISSUE THREAD

**Issue by kmeisthax** [telefang/telefang#118]
By default, Telefang renders to a 2x16 tile window, with odd lines missing 1 tile to fit the continue triangle. There are a few places in the base ROM that render text to a nonstandard window, and use manually formatted text in weird ways to get around the lack of window customization. We have added window width and height overrides to allow properly formatted text to render in these locations, and even to add our own custom windows. But the inserter is more-or-less oblivious to this.

We need to add a per-message width and height column, and modify the inserter to respect that particular line's width limit. The even/odd line width logic also needs to change to count all but the last line of a window as "even"; i.e., a Zukan entry needs to only subtract one tile off of the last line in every three-line page.

**Comment by obskyr** [comment]
I think the "even/odd" distinction is a bit misguided - in the case of normal text boxes, the fact that the odd line contains the "next page" graphic is a coincidence. The deciding factor is whether it's the *last* line or not.

Also important to note: the Field Guide does not need to shorten the last line, as the arrow graphic there is placed to the right of the text area, not within it.

**Comment by kmeisthax** [comment]
Even/odd should be renamed leading/trailing lines, yes.

I probably won't special-case field guide lines to not implement trailing line shortening though.

**Comment by obskyr** [comment]
Please do either special case the Field Guide or disable wrapping for that sheet entirely (since we now have Sheets-side wrapping) – there are a few entries that runneth over to the next page (and create a hanging one-word page) when they lack that last tile.
