### ISSUE TITLE
Scrolling for too long in the phone menu crashes the game

### ISSUE THREAD

**Issue by TagFreettle** [telefang/telefang#133]
When I continuously scroll through options in the phone menu the game will either crash with a black screen or show three green woman on the screen and put me in the menu used to dial in a phone number.
![bugged phone menu](https://user-images.githubusercontent.com/7492398/40261290-5e210ef4-5ac5-11e8-9a69-67225336d732.png)

**Comment by andwhyisit** [comment]
A fix has been added to the repo and is confirmed as working. Expect this bug to be absent from the v121 release when it comes out on the 15th of July.

**Comment by TagFreettle** [comment]
Nice, you actually tried to fix the game! That's cool.

**Comment by kmeisthax** [comment]
Well, it wasn't so much a bug in the game, as much as it was a bug we introduced when we added checks for the cartridge clock chip. It was difficult to track down and diagnose, which is why this bug has been open for so long.
