### ISSUE TITLE
Fusion/Lab Post-Evolution Names Fix

### ISSUE THREAD

**Issue by andwhyisit** [telefang/telefang#14]
2A:52A2 needs to be "ld de, $CCA3".
2A:52A8 needs to be "ld de, $CC90".
2A:52AD needs to be "ld de, $CCA3".
The sla rl sequence at 2A:52B9 needs to be replaced with 4 calls to $00EC.
2A:52C6 needs to be "ld c, $34".
2A:52C8 needs to be "ld b, $10".
In "script/battle/messages.messages.csv" the E5 codes need to be changed from <&0xca53> to <&0xcca3> and from <&0xca00> to <&0xcc90> in the "X has Fusion/Lab evolved" messages.
This also needs to be added in so that call works:

```
SECTION "BCx8", ROM0[$EC]
sla c
rl b
ret
```

**Comment by kmeisthax** [comment]
PR#62 has been merged in including this code. Is there any reason why I shouldn't close this issue?
