### ISSUE TITLE
Move Learnt Message Fix

### ISSUE THREAD

**Issue by andwhyisit** [telefang/telefang#15]
At 1D:4C09 "ld hl, $46F8" needs to become "ld hl, $5890".

**Comment by kmeisthax** [comment]
I think this might have been an artifact of the old patch - someone doubled the string buffer, but didn't relocate the table, and I had to replicate that in patch for the sake of the bytewise comparison. I should audit the codebase for anything else using StringTable_*_old symbols and remove them...
