### ISSUE TITLE
Level Pane Fix

### ISSUE THREAD

**Issue by andwhyisit** [telefang/telefang#16]
http://www.mediafire.com/file/653be4a0az0i1u4/levelscreenfix.zip
Inside the zip file is a tilemap to replace gfx/unknown/tilemap_0/77.csv (the level up pane tilemap).
Effectively the change removes excess tiles following the stat labels.
As a result this stops the garbage tiles from appearing after the stat labels.

**Comment by kmeisthax** [comment]
This isn't necessarily the way you suggested to fix the problem, but I wound up making the screen clear it's tiles, and then I expanded out the strings it draws, since @shokupanda will need that. There's now five tiles per line and you can put up to eight characters on them.
