### ISSUE TITLE
Tilemap Identification

### ISSUE THREAD

**Issue by andwhyisit** [telefang/telefang#17]
Call Backgrounds:
tilemap_0/45.csv = general field
tilemap_0/49.csv = cave
tilemap_0/4a.csv = ocean
tilemap_0/46.csv = forest
tilemap_0/4b.csv = desert

Battle Intro Backgrounds:
tilemap_0/3d.csv = general field
tilemap_0/41.csv = cave
tilemap_0/42.csv = ocean
tilemap_0/3e.csv = forest

Other:
tilemap_0/87.csv is the  "have my number plz" background.
tilemap_0/a.csv looks to be the full battle intro screen (including the header and message box). I can only assume that everything from the 5th row to the 12th is replaced by one of the battle intro background tilemaps.

**Comment by kmeisthax** [comment]
Moved and renamed the tilemap files to account for these.
