### ISSUE TITLE
Nickname Table Changes

### ISSUE THREAD

**Issue by andwhyisit** [telefang/telefang#19]
If you change F:4DB7 from "ld hl,$790E" to "ld hl,$7918" and insert each of the names from the spreadsheet in 6-byte blocks then everything should fit in exactly the same space. There were originally more name spaces, but most were blank, so I cut some fluff.

**Comment by kmeisthax** [comment]
As per a9cfaf9c1a7c22e350206d5713132afd1975e498 the nickname table now compiles and the really, really odd static memory lookup for the nickname table has been patched for the table expansion. I still need to get my hands on a suitable save file to test this...
