### ISSUE TITLE
"Ringtone/Original" & Link menu tilemap missing

### ISSUE THREAD

**Issue by Shokupanda** [telefang/telefang#22]
I can't seem to find the tilemap for the word "Ringtone" and "Original".
Same goes for the whole Link menu tilemap.

**Comment by Sanqui** [comment]
I have a vague memory stating that Ringtone and Original are written directly in code.

**Comment by andwhyisit** [comment]
Ringtone is 5 bytes uncompressed at 4:6081.
Original is 5 bytes uncompressed at 4:6086.

Neither are in the disassembly.

**Comment by andwhyisit** [comment]
The link menu can be found in the following:
gfx/menu/link_error_tmap.csv (shown when the connection is interrupted)
gfx/menu/multiplayer_tmap.csv (this is the full menu tilemap)
gfx/menu/multiplayer/melody_transfer_tmap.csv (this is the individual melo-d button tilemap)
gfx/menu/multiplayer/trade_tmap.csv (this is the individual trade button tilemap)
gfx/unknown/tilemap_0/95.csv (this is the individual vs button tilemap)

The last 3 are copies of the individual buttons from multiplayer_tmap.csv, so don't forget to copy any changes to those buttons into their respective individual tilemaps.

**Comment by kmeisthax** [comment]
To change these two tilemaps, look at the bottom of components/melodyedit/ringtone_menu.asm - they're denoted with .ringtone and .original, respectively. You can't lengthen them unless you add advice code.
