### ISSUE TITLE
Using all 8 characters in name glitches out

### ISSUE THREAD

**Issue by SoraHjort** [telefang/telefang#227]
Patch Version: v127
Emulator: VBA-M 2.1.0

IPS Patchers tried (Though it probably doesn't matter)
    -Lunar IPS
    -Floating IPS
    -VBA-M's Live Patching

Description: When using all the character slots when naming the protagonist, the game starts to glitch out. From Dialog overlapping itself, to corrupting the Dialogs, to glitching out the world's tiles, as well as straight up locking the game.

The severity of some of the glitching changes depending on the time set to the clock, possibly the name as well. However in all tests, the game will lock up in the dialog after the protagonist approaches the tree.

Suspicion: Using the eighth character leads into a overflow, which would explain some occurrences, such as when the name shows up it starts outputting garbage text.

Video Demonstrations
Speed Version - https://youtu.be/sTsMVQjmMzI (The Dialog actually managed to fix itself at one point for a little bit, which was a first time I ran into that, still broke by the end)
Power Version - https://youtu.be/3_9KKDRFKsA

Closing: I didn't see this bug in the known issues list, nor I wasn't able to see anything in opened and closed issues. If I missed this bug previously being reported, I apologize.

**Comment by kmeisthax** [comment]
I believe c8e7f124eb518b2a16259d7b7a301289e8ec0298 or a related commit fixed this - we're releasing a new version Friday, so I'll double-check tonight with the latest version.

If you want to test the latest version yourself, or just wanna get past this bug, you can grab the latest patch off of Paparouna here: https://paparouna.fantranslation.org/#/builders/3/builds/244

**Comment by kmeisthax** [comment]
Yeah, I just ran the tip of patch and that behavior does not occur. Tried it in bgb in both CGB and SGB modes, and I grabbed VBA-M 2.1 and ran it in both CGB and SGB modes. I think it's safe to say this bug was already fixed - though I'll wait for you to confirm before I close the issue. Thanks for the detailed bug report, though!

**Comment by SoraHjort** [comment]
Yep, looks like the update has it fixed. Thanks for the help. Look forward to the new version~
