### ISSUE TITLE
Tilemaps - part 3

### ISSUE THREAD

**Issue by andwhyisit** [telefang/telefang#23]
versions/power/gfx/unknown/tilemap_0/56.csv = Game Over (Crypto)
versions/speed/gfx/unknown/tilemap_0/56.csv = Game Over (Fungus)

That should finish off all the version-specific tilemaps.

gfx/unknown/tilemap_0/19.csv = Name entry "lower" overlay (thanks Shokupanda)
gfx/unknown/tilemap_0/13.csv = Name entry "UPPER" overlay
gfx/unknown/tilemap_0/14.csv = Name entry "123" overlay
gfx/unknown/tilemap_0/37.csv = The Denjuu nickname entry screen

gfx/unknown/tilemap_0/95.csv is the vs button individual tilemap (on the link screen).

gfx/unknown/tilemap_0/54.csv is the header and message box for the "got X's phone number" screen.

gfx/unknown/tilemap_0/1b.csv is "empty_menu_tilemap.csv" rotated down 1 tile (or up 2).
gfx/unknown/tilemap_0/1c.csv is "empty_menu_tilemap.csv" rotated up 1 tile (or down 2).
These are used for the menu scrolling animation.

gfx/unknown/tilemap_0/4d.csv is the screen where you assign a ringtone to a Denjuu.

**Comment by kmeisthax** [comment]
Minor note: In the master branch, the following are a bit different: Tilemap 0/14 is actually "Katakana", tilemap 0/13 is "Hiragana", and tilemap 0/19 is numbers. In patch we will rename and shift them around to match.

**Comment by kmeisthax** [comment]
That should be everything for master and patch.
