### ISSUE TITLE
Add status tiles to patch

### ISSUE THREAD

**Issue by andwhyisit** [telefang/telefang#25]
http://andwhyisit.bugsiteguardian.com/tulunk/statustable.png

**Comment by kmeisthax** [comment]
The graphics themselves were added in 3a5e46bfb514f4a3527f4b4cd1ad5684f02da759 but the code to replace them in battle doesn't exist yet. Tagging as disassembly needed for now...

**Comment by kmeisthax** [comment]
I've been seeing these things in battle, so I'm going to assume this is closeable
