### ISSUE TITLE
Game Over screen does not initialize a color palette in SGB mode

### ISSUE THREAD

**Issue by Blaziken257** [telefang/telefang#295]
When playing on a Super Game Boy, the Game Over screen does not initialize a color palette at all (no packets are sent to the SGB), so the palette remains the same as the previous screen.

If this is a result of losing a Telefang against another T-Fanger, the Game Over screen has a glitchy palette.

![bgb00527](https://user-images.githubusercontent.com/2187686/59738430-11f95700-9216-11e9-9a45-3472b5b6c441.png)

If this is result of losing all contacts, the effects are less severe and has a solid palette instead.

![bgb00523](https://user-images.githubusercontent.com/2187686/59738447-20e00980-9216-11e9-930b-3f573821ab9d.png)

**Comment by andwhyisit** [comment]
The game over screen is now coloured, so this issue can now be closed.
