### ISSUE TITLE
Enemy Denjuu's name shares the same palette as the Denjuu in SGB mode

### ISSUE THREAD

**Issue by Blaziken257** [telefang/telefang#300]
In a Telefang on SGB mode, the palette of the Denjuu's name is the same as the palette of the Denjuu itself (palette 3). This is noticeable when the darkest color of the enemy Denjuu is not black. The player's Denjuu does not have this issue: The Denjuu itself uses palette 2, while the name uses palette 0 (the same as the HP/DP bars).

In the example below, notice that Keshi has dark gray text instead of black.
![bgb00529](https://user-images.githubusercontent.com/2187686/59902982-9255be80-93b4-11e9-8e25-b5ab5329fb0c.png)

**Comment by Blaziken257** [comment]
This also extends to a Denjuu's status effect as well as the arrows to the left and right of the name.

![bgb00532](https://user-images.githubusercontent.com/2187686/59903269-64bd4500-93b5-11e9-8234-759479714cff.png)

**Comment by andwhyisit** [comment]
The fix messed up the colours for attack animations, so this issue shall be reopened until that is addressed.
