### ISSUE TITLE
Question options in dialogue are misaligned

### ISSUE THREAD

**Issue by kmeisthax** [telefang/telefang#31]
(Imported from the Wiki)

Andwhyisit suggested adding manual formatting opcodes for questions. We may also need to add a facility for questions that occupy one line for each option.

**Comment by andwhyisit** [comment]
I have added a control code (ED) that should be able to handle the positioning of options, but it needs a replace code to be added to the script parser in order to use it.

**Comment by andwhyisit** [comment]
Short answers have been handled. Long answers will still require a vertical selection mode.

**Comment by kmeisthax** [comment]
I'm almost ready to close this, since we added vertical and horizontal formatting for questions. I need to know how to format them, though, since we have a bunch of messages in the translation that didn't get formatted with these codes. Most of them are UI related.

**Comment by andwhyisit** [comment]
The UI arrows were fixed and an option formatting tool was made. We can retire this issue.
