### ISSUE TITLE
Contact enlist screen cannot handle long Denjuu names

### ISSUE THREAD

**Issue by kmeisthax** [telefang/telefang#35]
(Imported from the Wiki)

"The 'Got X's phone number!' text in the message box seems to truncate Denjuu names."

**Comment by andwhyisit** [comment]
Under "Victory_CopyIntoArg1::" in components/victory/participant_utils.asm "ld b, 9" should be "ld b, $11". This will fix this issue.

**Comment by kmeisthax** [comment]
Yay for more old patch stuff that didn't bother to change the size parameter
