### ISSUE TITLE
Long move names overflow their tile allocations on Status screen

### ISSUE THREAD

**Issue by kmeisthax** [telefang/telefang#37]
(Imported from the Wiki)

"The moves 'Numbing Sting' and 'Harpoon Missile' are too long. 'Harpoon Missile' in particular causes graphical issues on Denjuu stat pages."

Given that this screen pulls from the attack names, we may need to introduce an abbreviated attack name table, or have the code stop drawing after a length limit (e.g. autoformatting).

**Comment by kmeisthax** [comment]
@andwhyisit added a thinner font in ef2157f21d0983422657e7793e61b2e825898296 which can be enabled or disabled in code. Plan is to make the status screen shrink attack names to fit.

**Comment by kmeisthax** [comment]
<img width="160" alt="tf117_condensedbattlemoves" src="https://user-images.githubusercontent.com/108736/37190054-a721f294-2325-11e8-80d7-2aecc4affad8.png">

As of 7ff11078e922 all text strings drawn using DrawName75, DrawShortName, or DrawCenteredStagedString will be subject to automatic sizing & font condensation. This fixes the long string issue here and maybe a few other places.

**Comment by Sanqui** [comment]
<3
