### ISSUE TITLE
Text inserter should strip whitespace in messages

### ISSUE THREAD

**Issue by kmeisthax** [telefang/telefang#40]
(Imported from the Wiki)

Some lines have leading spaces. It may be safe to remove them in the inserter.

However, I would also be worried about manually formatted lines with spaces in them. Bugsite has the opposite problem where manually formatted lines don't get centered because bvm strips whitespace in autoformatted lines. We would need additional inserter support for retaining those kinds of lines, if they exist.

**Comment by andwhyisit** [comment]
I believe the lines with leading spaces might have been text bugs that were fixed a while back rather than real leading whitespace in the spreadsheet. For now this issue should be closed until the issue it talks about is the real deal.
