### ISSUE TITLE
Translate "zukan" as "Field Guide" instead of "Index"

### ISSUE THREAD

**Issue by kmeisthax** [telefang/telefang#41]
Suggested by @obskyr. This is actually more difficult than it looks; the entire Pause Menu text resource needs to be redrawn and tiles remapped to fit this code. The existing resource already reuses tiles to save space, so there's no more room for that option to span the whole button. Also, text used by the save menu needs to be moved into a separate graphical resource. This also impacts patch_de, which is doing the same thing but in German.

**Comment by kmeisthax** [comment]
@obskyr Could you post your proposed "Field Guide" bitmap here?

**Comment by obskyr** [comment]
These were the ones I put together earlier:

![main1](https://user-images.githubusercontent.com/4363779/35802693-4c9cfdae-0a71-11e8-81c6-763f45d6c6bd.png)
![main1_dmg](https://user-images.githubusercontent.com/4363779/35802695-4cb7b946-0a71-11e8-98d9-a49d434d2714.png)
![main2](https://user-images.githubusercontent.com/4363779/35802697-4cd2ef54-0a71-11e8-9f1e-29313d6728cb.png)
![main2_dmg](https://user-images.githubusercontent.com/4363779/35802691-4c729fbe-0a71-11e8-978d-56c2e08c1740.png)

"Field" is in main 1; "Guide" is in main 2.

**Comment by kmeisthax** [comment]
The Field Guide graphic is now implemented, as well as some other graphical cleanups.
