### ISSUE TITLE
"Unidentified" and "NO ITEMS" gfx missing

### ISSUE THREAD

**Issue by Shokupanda** [telefang/telefang#49]
For the german patch I need the PNG for the "Unidentified" graphic aswell as the "NO ITEMS" graphic.

**Comment by obskyr** [comment]
"NO ITEMS" can be found in `gfx/items/1/33.png`. "Unidentified" does seem to need to be extracted, however...

**Comment by Sanqui** [comment]
"Unidentified" is the last Denjuu graphic, for what it's worth.

**Comment by obskyr** [comment]
Oh, cool! There's been some talk of breaking out all of the Denjuu sprites into PNGs, so we might as well do that while we're at it.

**Comment by kmeisthax** [comment]
For those watching on Github: @obskyr has been working on upstream changes to rgbgfx to allow us to generate palettes from indexed PNG files correctly. Extraction of denjuu battle sprites is blocked on rednex/rgbds releasing that code as a binary and kmeisthax/CodeModule being updated to the latest rgbds's object module format.

**Comment by kmeisthax** [comment]
RGBDS has updated to 0.3.6 including @obskyr's changes so we can now move forward on this.

**Comment by obskyr** [comment]
With #120, the "UNIDENTIFIED" graphic can now be found in `gfx/denjuu/174.color.png`.

**Comment by kmeisthax** [comment]
@Shokupanda I updated patch_de with the latest commits and a merge from master. All you need to is pull telefang/patch_de & go wild
