### ISSUE TITLE
Map screen needs to support longer text strings

### ISSUE THREAD

**Issue by kmeisthax** [telefang/telefang#67]
As per @andwhyisit and @obskyr: https://twitter.com/obskyr/status/966274887756206082

We need to extend this text box to support two lines of text, or support one-line paging. Or, in the worst-case, condense our translations to fit.

**Comment by obskyr** [comment]
After talking a bit to @andwhyisit, I think we've come to the conclusion that we should condense our translations. We've come up with good alternatives to all the names that were too long - plus, none of the names were more than a few characters too long.

**Comment by kmeisthax** [comment]
@Shokupanda Before I close this issue, can you confirm that all map translations will fit in one line on patch_de?

**Comment by obskyr** [comment]
Now that we have the narrow font, this is *almost* certainly not needed. Definitely not for English.

**Comment by kmeisthax** [comment]
Patch 117 launched with some lines that still don't fit. Changing this to "autocondense map names" and marking for Patch 118.

**Comment by kmeisthax** [comment]
<img width="160" alt="tf119_condensedmaptitle" src="https://user-images.githubusercontent.com/108736/39608364-ed82979c-4f0e-11e8-8969-6d69777ae2d1.png">
