### ISSUE TITLE
A button works even on 1-page Field Guide entries

### ISSUE THREAD

**Issue by obskyr** [telefang/telefang#69]
Take any Field Guide entry with only enough text for one page. Press the A button on that page, and the text will redraw from scratch. Of course, pressing A should do nothing on 1-page entries.

**Comment by kmeisthax** [comment]
I was originally going to comment that we can't fix this because we need wraparound and the text machinery doesn't store if it has overflowed it's text box or not, but then I realize that it totally does, but indirectly. closed as per ed2f4b5
