### ISSUE TITLE
Right-justify habitat on Field Guide screens

### ISSUE THREAD

**Issue by obskyr** [telefang/telefang#71]
![Left-justified "Sky"](https://user-images.githubusercontent.com/4363779/36553354-6585558a-17fc-11e8-88aa-c50c0dc439ee.png)

"Sky" would look better to the right, as discussed in chat.

**Comment by kmeisthax** [comment]
<img alt="tf117rightalignedhabitat" src="https://user-images.githubusercontent.com/108736/36942897-9819ab2a-1f4c-11e8-8730-1e5598f4ddf8.png">

Implemented in 3b74df1a31584c926208b5d9dc6e997fb0c8403a
