### ISSUE TITLE
Put Field Guide Denjuu names in sprites and add 4 pixels of top margin

### ISSUE THREAD

**Issue by obskyr** [telefang/telefang#72]
![Wow!](https://user-images.githubusercontent.com/4363779/36553740-6c39f5a6-17fd-11e8-84f4-87fd3cfca24e.png)

The Denjuu name would look much better centered vertically between the top edge and the Denjuu type graphics, so put it in 8 sprites and offset it by +4 pixels vertically.

**Comment by kmeisthax** [comment]
@obskyr You were working on this in chat the other day. Can I expect a PR of this soon?

**Comment by kmeisthax** [comment]
<img width="160" alt="tf117completedzukan" src="https://user-images.githubusercontent.com/108736/37009704-23596d78-20b6-11e8-904f-9411679591a1.png">

Fixed as of too many commits to mention
