### ISSUE TITLE
Field Guide doesn't allow a following page if the last line of the current page is empty.

### ISSUE THREAD

**Issue by obskyr** [telefang/telefang#92]
Take this hypothetical entry for Waratah, for example:

```
<S0>Its hat is its trademark.

Its face and its butt are both heart-shaped.<*4>
```

That gets formatted as following:

```
Its hat is its
trademark.

Its face and its butt
are both heart-shaped.
```

However, as you can see here, it's impossible to go to the second page:

![Demonstration](https://user-images.githubusercontent.com/4363779/37026211-fc6e7316-212d-11e8-9c44-0d5f430c2640.png)

This has to do with how the inserter determines how to handle cross-page linebreaks, as the finished ROM doesn't even contain the second page. Some Field Guide entries, like Waratah's, benefit from being able to page break in the middle, so this should be fixed.

**Comment by kmeisthax** [comment]
As of ebeeb5cad490 you can now use repeated newlines and it just works
