### ISSUE TITLE
Grammar: Articles

### ISSUE THREAD

**Issue by Sanqui** [telefang/telefang#99]
Battle messages should use proper articles.

0x114000
**Current**: "Keshi apeared!"
**Correct**: "A Keshi apeared!"
**Correct**: "An Oshe appeared!"
**Correct**: (for event battles): "Golaking has challenged you!"
Solution: An article table for each Denjuu (a/an). Set a flag on the script opcode that invokes a Denjuu battle to use the alternative message.

0x1140e2
**Current**: "Kakuza Party Member has challenged you!"
**Correct**: "The Kakuza Party Member has challenged you!"
**Correct**: "Tabasco has challenged you!"
Solution: An article table for each T-Fanger (The/nothing).

The rest of battle messages need to use no article for player Denjuu and _the_ for enemy Denjuu.  Rationale: T-Fanger Denjuu sometimes have nicknames referenced in dialogue, but these are not used in battle.  Therefore the name in battle is the species name and needs an article.

**Comment by andwhyisit** [comment]
0x114000 and 0x1140e2 are dealt with. All that remains is to determine whether the in-battle messages are for the opponent or player Denjuu and conditionally load articles to suit.

**Comment by andwhyisit** [comment]
I think for now we can probably close this.
